####################################################
# Description: Linux makefile for skiplist.
####################################################

all:
	gcc skiplist.h skiplist.c skiplist_test.c -o skiplist

clean:
	rm skiplist
